### ISSUE TITLE
Getting the attached error

### ISSUE THREAD

**Issue by argrithmag** [Syndicate-Consulting/UniFi-on-Azure#4]
While deploying, I get the following error:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"InaccessibleImage","message":"The image 'jacobalberty/unifi:stable' in container group 'unificontainer' is not accessible. Please check the image and registry credential."}]}

**Comment by s3bast1aan** [comment]
Hi @argrithmag,

By bad for having overlooked this issue. Thanks for reporting it and pointing out the solution. :)
